### PR TITLE
fix: add boolean as acceptable query priority type

### LINKED ISSUE #166: Firebase Query equalTo does not support booleans
```
Error: Query.startAt failed: first argument must be a valid firebase priority (a string, number, or null).
at assertQuery (/home/redmega/Work/astral/astral/node_modules/firebase-mock/src/query.js:178:11)
```

Firebase itself supports booleans as values and as query values.

### PR DESCRIPTION
**Pull request by Redmega**
Resolves #166

### CODE REVIEW

**Comment by dmurvihill** [comment]
Thanks @Redmega. We're migrating away from this repo, but I opened and merged [companion PR](https://github.com/dmurvihill/firebase-mock/pull/45) on my fork, which we are using to publish. Look for this in 3.0.0 and 2.3.1.

**Comment by Redmega** [comment]
You might want to hold off on that @dmurvihill 

I added a proper test and it's not giving the expected result. I need to look into why.

**Comment by Redmega** [comment]
Do you want me to open a PR to that fork and move discussion there?

**Comment by dmurvihill** [comment]
Yes, go ahead and reopen over there if you don't mind.

I've been looking into this; I think the `priorityComparator` method (`utils.js:64`) is incomplete. It seems to be interested only in priorities of type `null`, `string`, and `number`, ignoring boolean and object values in spite of the [Firebase docs](https://firebase.google.com/docs/database/web/lists-of-data#sort_data).

There may (not sure) also be a problem with `Slice.prototype._inRange` (`slice.js:85`) which might be doing an exclusive rather than an inclusive range.

**Pull request closed without merging**
