### PR TITLE
Fix for #110

### LINKED ISSUE #110: Updates being with slashes are throwing errors
The real Firebase RTDB allows updates to being with `/`, this mock library however does not :(

Test case that fails available [here](https://github.com/bookcreator/firebase-mock/tree/slashes):

```javascript
    it('can work with nested paths beginning with /', function () {
      var update = {};
      update['some/prop/withoutSlash'] = 12;
      update['/some/prop/withSlash'] = 12;
      ref.update(update);
      ref.flush();
      expect(ref.getData().some.prop).to.eql({withoutSlash: 12, withSlash: 12});
    });
```

Error:

```
AssertionError [ERR_ASSERTION]: A child path is required
      at MockFirebase.child (src/firebase.js:9:9143)
      at MockFirebase._addChild (src/firebase.js:9:36552)
      at MockFirebase._updateOrAdd (src/firebase.js:9:35853)
      at src/firebase.js:9:29500
      at Array.forEach (<anonymous>)
      at MockFirebase._dataChanged (src/firebase.js:9:29086)
      at MockFirebase.<anonymous> (src/firebase.js:9:12822)
      at FlushEvent.run (src/queue.js:9:3118)
      at process (src/queue.js:9:2039)
      at FlushQueue.flush (src/queue.js:9:2359)
      at MockFirebase.flush (src/firebase.js:9:3770)
      at Context.<anonymous> (test/unit/firebase.js:554:11)
```

### PR DESCRIPTION
**Pull request by rhodgkins**
Fixes #110

### CODE REVIEW

**Comment by soumak77** [comment]
Since this is very close to the same issue as in #97, could you possibly fix that issue as well in this PR? If not, no worries.

**Comment by rhodgkins** [comment]
@soumak77 I'll take a look!

I think the fix for #110 is sound - it's what I was doing as a work around before submitting this PR 👍

**Comment by soumak77** [comment]
@rhodgkins agreed, unit tests prove its working!  I'll merge this PR and release a new version.

**Comment by rhodgkins** [comment]
@soumak77 I've fixed #97 too, bear with!

**Pull request merged**
